# Generated by Django 4.0.8 on 2022-11-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userslug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
