# Generated by Django 4.0.8 on 2022-11-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_customuser_userslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='userslug',
        ),
    ]
