# Generated by Django 4.0.8 on 2022-12-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_customuser_userslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='C:\\Users\\lizas\\Downloads\\unnamed.png', upload_to='photos/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
    ]
